## Quiz Instructions

Welcome to the FRE 521D Quiz 1! Please follow the instructions carefully:

### **Objective**:
This quiz is designed to test your understanding of data preprocessing and exploratory data analysis techniques using the **Wine Quality Dataset**. You will work with both **numerical** and **categorical** features.

### **Marks**:
- total Marks - 20 (will be converted to 10 during final grading)
- Each cell mentions the mark for the question, `e.g, [2]`

---

## Name - 
## ID - 

---

### **Steps**:
1. **Download and Fill Details**:
   - Download this notebook to your local machine.
   - Fill in your **Name** and **Student ID** in the designated cell at the top.

2. **Run Initial Setup**:
   - Run the first few cells, including those that import required libraries and load the dataset.
   - If any package-related errors occur, refer to the official **Anaconda Documentation** to resolve them (e.g., install missing libraries).
   - If you require any additional libraries, import them as you go. 

3. **Code and Execute**:
   - For each task provided in this notebook, write your Python code in the designated cell.
   - Run the cell to check the output.

4. **Submission**:
   - Save and submit the completed notebook via the provided submission link before the **deadline: January 16, 11:59 PM PST**.

---


### **Tasks**:
- There are 10 questions in this Notebook labelled as `Q`; you need to answer all of them.
- Write python codes to each empty cell to answer the questions.


### **Important Notes**:
- Ensure your notebook is clean, well-documented, and runs without errors.
- Late submissions will not be accepted.

Good luck!

## Run this cell and load the data (Do not change anything in this cell)

In [1]:
import numpy as np
from sklearn.datasets import load_wine
import pandas as pd

# Load the Wine dataset from sklearn
wine_data = load_wine(as_frame=True)  # Load the dataset as a Pandas DataFrame
wine_df = wine_data.frame  # Access the DataFrame

wine_df.rename(columns={'target': 'class'}, inplace=True)
wine_df['quality_category'] = pd.cut(
    wine_df['class'],  
    bins=[-1, 0.5, 1.5, 2.5],  
    labels=['Low Quality', 'Medium Quality', 'High Quality']
)
np.random.seed(42)
m = 0.3
total_cells = wine_df.size
num = int(total_cells * m)
random_rows = np.random.randint(0, wine_df.shape[0], size=num)
random_cols = np.random.randint(0, wine_df.shape[1], size=num)
for row, col in zip(random_rows, random_cols):
    wine_df.iloc[row, col] = np.nan

wine_df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class,quality_category
0,NaN,NaN,2.43,NaN,127.0,2.80,NaN,0.28,NaN,5.64,1.04,3.92,1065.0,0.0,Low Quality
1,13.20,1.78,NaN,11.2,100.0,2.65,2.76,NaN,1.28,NaN,1.05,NaN,1050.0,0.0,NaN
2,13.16,NaN,2.67,NaN,101.0,2.80,NaN,0.30,2.81,NaN,1.03,3.17,1185.0,NaN,Low Quality
3,14.37,1.95,NaN,NaN,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,NaN,0.0,NaN
4,13.24,2.59,NaN,21.0,118.0,2.80,2.69,0.39,1.82,NaN,NaN,2.93,NaN,NaN,Low Quality

Your Dataframe name is `wine_df`, use this name to proceed further

## Dataset Description

In [42]:
from sklearn.datasets import load_wine

# Load wine dataset
wine_data = load_wine()
print(wine_data.DESCR)  # Print dataset description

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2

    :Summary Statistics:

    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            10.6  30.0    19.5   3.3
    Magnesium:                    70.0 162.0    99.7  14.3
    Total Phenols:                0.98  3.88    2.29  0.63
    Flavanoids:                   0.34  5.08    2.03  1.00
    Nonflavanoid Phenols:         0.13  0.66    0.36  0.12
    Proanthocyanins:              0.41  3.58    1.59  0.57
    Colour Intensity:              1.3  13.0     5.1   2.3
    Hue:                          0.48  1.71    0.96  0.23
    OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71
    Proline:                       278  1680     746   315
    ============================= ==== ===== ======= =====

    :Missing Attribute Values: None
    :Class Distribution: class_0 (59), class_1 (71), class_2 (48)
    :Creator: R.A. Fisher
    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
    :Date: July, 1988

This is a copy of UCI ML Wine recognition datasets.
https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data

The data is the results of a chemical analysis of wines grown in the same
region in Italy by three different cultivators. There are thirteen different
measurements taken for different constituents found in the three types of
wine.

Original Owners:

Forina, M. et al, PARVUS -
An Extendible Package for Data Exploration, Classification and Correlation.
Institute of Pharmaceutical and Food Analysis and Technologies,
Via Brigata Salerno, 16147 Genoa, Italy.

Citation:

Lichman, M. (2013). UCI Machine Learning Repository
[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,
School of Information and Computer Science.

.. topic:: References

  (1) S. Aeberhard, D. Coomans and O. de Vel,
  Comparison of Classifiers in High Dimensional Settings,
  Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of
  Mathematics and Statistics, James Cook University of North Queensland.
  (Also submitted to Technometrics).

  The data was used with many others for comparing various
  classifiers. The classes are separable, though only RDA
  has achieved 100% correct classification.
  (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data))
  (All results using the leave-one-out technique)

  (2) S. Aeberhard, D. Coomans and O. de Vel,
  "THE CLASSIFICATION PERFORMANCE OF RDA"
  Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of
  Mathematics and Statistics, James Cook University of North Queensland.
  (Also submitted to Journal of Chemometrics).

In [54]:
## Q1: Find the total number of rows and columns [1].

In [56]:
## Q2: Identify columns with missing values and Calculate the percentage of missing values for each column. [2].

In [ ]:
## Q3: Handle the Missing values [3]

In [ ]:
## Q4: Summarize the dataset after handling missing values. [2]

In [ ]:
## Q5: Create interactive graphs using this dataset [3]

In [ ]:
## Q6: Explain the relationship between different features [3]

In [ ]:
## Q7: Do we need to handle the outliers in this dataset? [2]

In [ ]:
## Q8: Identify categorical variables and convert them to numeric value [2]

In [ ]:
## Q9: Explain the quality of the dataset [1]

In [ ]:
## Q10: Save the new dataframe in a excel file [1]

End of Quiz 1!